Repository cloudposse/terraform-aws-vpc, pull requests merged in 2022-10, with the labels that each got.

#110 add/default-route-table
  README.md
  docs/terraform.md
  examples/complete/fixtures.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/variables.tf
  main.tf
  outputs.tf
  test/src/go.sum
  variables.tf
Labels: minor

#112 Drop support for deprecated features, revamp VPC Endpoint support
  .github/workflows/validate-codeowners.yml
  README.md
  docs/migration-v1-v2.md
  docs/terraform.md
  examples/complete/main.tf
  examples/complete/versions.tf
  examples/vpc-endpoints/main.tf
  examples/vpc-endpoints/outputs.tf
  examples/vpc-endpoints/versions.tf
  main.tf
  modules/vpc-endpoints/README.md
  modules/vpc-endpoints/main.tf
  modules/vpc-endpoints/outputs.tf
  modules/vpc-endpoints/variables.tf
  modules/vpc-endpoints/versions.tf
  test/src/Makefile
  test/src/examples_deprecated_test.go
  test/src/examples_vpc_endpoints_test.go
  test/src/go.mod
  test/src/go.sum
  variables-deprecated.tf
  variables.tf
  versions.tf
Labels: no-release

#113 Fix output description
  README.md
  docs/terraform.md
  outputs.tf
Labels: patch
